## NumPy Exercises
The examples here are summarized from the book Python Machine Learning (Wei-Meng Lee)

In [ ]:
import numpy as np

### Creating NumPy Arrays

In [ ]:
a1 = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
a1.shape # (10,)
type(a1) # numpy.ndarray
type(a1[0]) # numpy.int64
len(a1) # 10

a2 = np.arange(1,10,3) # [1 4 7]

a3 = np.zeros(5) # [0. 0. 0. 0. 0.]

a4 = np.zeros((2,3))
# [[0. 0. 0.]
#  [0. 0. 0.]]
a4.shape # (2, 3)
type(a4) # numpy.ndarray

a5 = np.full((2,3), 8)
# [[8 8 8]
#  [8 8 8]]

a6 = np.eye(3)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

a7 = np.random.random((2,3))
# [[0.34229659 0.16823129 0.46873795]
#  [0.5016274  0.62467579 0.37549322]]

list1 = [1,2,3,4]
a8 = np.array(list1) # [1 2 3 4]
type(list1) # list
type(a8) # numpy.ndarray

a9 = np.array([[1,2,3,4], [5,6,7,8]])
# [[1 2 3 4]
#  [5 6 7 8]]

### Array Indexing

In [ ]:
a1 = np.array([1,2,3,4])
a1[0] # 1
a1[1] # 2
type(a1[0]) # numpy.int64

a2 = np.full((2,3), 8)
a2[0] # [8 8 8]
a2[0,0] # 8
a2[0][0] # 8
type(a2[0]) # numpy.ndarray
type(a2[0,0]) # numpy.float64

a3 = np.array([[1,2,3,4], [5,6,7,8]])
a3[0, [1,3]] # [2 4]
a3[:, 0] # [1 5]
type(a3[:, 0]) # numpy.ndarray

### Boolean Indexing

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1>2 # [False False  True  True  True  True]
a1[a1>2] # [3 4 5 6]

even_nums = a1[a1 % 2 == 0] # [2 4 6]

### Slicing Arrays

In [ ]:
a1 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]

a1[0:2, :3] # select rows 0 to 2 (2 is not included), and first 3 columns
# [[1 2 3]
#  [6 7 8]]
a1[-2:, :3] # select last 2 rows and first 3 columns
# [[ 6  7  8]
#  [11 12 13]]
a1[:, :2] # select all rows and first 2 columns
# [[ 1  2]
#  [ 6  7]
#  [11 12]]

### NumPy Slice is a Reference

In [ ]:
a1 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

a2 = a1[2:, 2:] # select a subset, rows its index start from 2, and columns its index start from 2
# [[13 14 15]]
a2[0, 1] = 999

a1 # Since the subset is a reference, changes affect the original value
# [[  1   2   3   4   5]
#  [  6   7   8   9  10]
#  [ 11  12  13 999  15]]

### Reshaping Arrays

In [ ]:
a1 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
a1.reshape((1, -1)) # [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
a1.reshape((-1, 1))
# [[ 1]
#  [ 2]
#  [ 3]
#  ...]
a1.reshape((5, 3)) # same with a1.reshape((5, -1))
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]
#  [13 14 15]]
a2 = a1.view() # Shallow copy (not a deep copy). Reshaping does not affect the copy.
a1[0,0] = 99
a1.shape = 1, -1 # "shape" property has set function. It reshapes itself.

a1 # [[ 99  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
a2
# [[99  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]

### Array Math

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])
# [[1 2 3]
#  [4 5 6]]
a2 = np.array([[7,8,9],[10,11,12]])
# [[ 7  8  9]
#  [10 11 12]]

a1 + a2 # Element-wise summation
# [[ 8 10 12]
#  [14 16 18]]
a1 * a2 # Element-wise multiplication
# [[ 7 16 27]
#  [40 55 72]]

### Matrix

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[1,2],[3,4],[5,6]])

np.dot(a1, a2) # Matrix multiplication [2x3] x [3x2] = [2x2]
# [[22 28]
#  [49 64]]

# matrix class is a subclass of ndarray. It is restricted to 2 dimensional array.
m1 = np.matrix([[1,2,3],[4,5,6]])
m2 = np.matrix([[1,2],[3,4],[5,6]])
type(m1) # <class 'numpy.matrix'>
m1 * m2 # Matrix multiplication
# [[22 28]
#  [49 64]]

### Cumulative Sum

In [ ]:
a1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
a1.cumsum()
# [ 1  3  6 10 15 21 28 36 45]
a1.cumsum(axis=0) # Column cumsum
# [[ 1  2  3]
#  [ 5  7  9]
#  [12 15 18]]
a1.cumsum(axis=1) # Row cumsum
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

### NumPy Sorting

In [ ]:
a1 = np.array([3,1,8,2,0,0,5])
a2 = np.sort(a1) # a1 is not modified
# [0 0 1 2 3 5 8]
a1.sort() # a1 is now modified. sort function does not return anything

a2 = np.array([12, 5, 14, 8, 6])
indices = a2.argsort() # It returns the item indices for the sorted array
# [1 4 3 0 2]
a2[indices] # Returns a sorted array without modifying the original array
# [ 5  6  8 12 14]
a2[indices][::-1] # to get the reverse order, [::-1] can be used
# [14 12  8  6  5]

a3 = np.array([[3,7,2], [9,1,5]])
s1 = np.sort(a3)
# [[2 3 7]
#  [1 5 9]]
s2 = np.sort(a3, axis=0) # Sorts columns as we expected
# [[3 1 2]
#  [9 7 5]]

### Deep Copy

In [ ]:
list1 = [[3,7,2], [9,1,5]]
a1 = np.array(list1)
a2 = a1.copy()

list1[0][0] = 99 # Does not affect or has side effect at all.
a1[0][0] = 99 # Does not change a2 or list1
a1
# [[99  7  2]
#  [ 9  1  5]]
a2
# [[3 7 2]
#  [9 1 5]]